services:
  mysql:
    image: mysql:8.0
    container_name: mysql-kunden
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kunden_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"     # Host 3307 -> Container 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kunden-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kunden_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_0900_ai_ci
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SERVER_PORT: 8090
    ports:
      - "8090:8090"    # Host 8090 -> Container 8090
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kunden-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"      # Host 4200 -> Container 80 (NGINX)
    restart: unless-stopped

volumes:
  mysql_data:
